version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # where your package.json is
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5